version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rr_development
      MYSQL_USER: rr_user 
      MYSQL_PASSWORD: rr_password

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/srv/app
    ports:
      - "8080:8080"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/srv/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
