version: '3.4'

x-database-common-variables: &database-common-variables
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: rr_user 
    MYSQL_PASSWORD: rr_password

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"    
    environment:
      <<: *database-common-variables
      MYSQL_DATABASE: rr_development

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/srv/app
    ports:
      - "8080:8080"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/srv/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
 
  guard:
    image: reservation_responsable_web:latest
    command: guard #bundle exec guard --no-bundler-warning --no-interactions
    volumes:
      - .:/srv/app
    environment:
      <<: *database-common-variables
      MYSQL_DATABASE: app_test
      RAILS_ENV: test
    depends_on:
      - db
